# These are supported funding model platforms

github: [xbox002000]  # Replace or add your GitHub username for the Sponsor button
# patreon: # Replace with a Patreon username
# open_collective: # Replace with an Open Collective username
# ko_fi: # Replace with a Ko-fi username
# tidelift: # Replace with a Tidelift platform name
# community_bridge: # Replace with a Community Bridge project name
# liberapay: # Replace with a Liberapay username
# issuehunt: # Replace with an IssueHunt project name
# lfx_crowdfunding: # Replace with an LFX Crowdfunding project name
# polar: # Replace with a Polar username
# custom: ['https://your-custom-link.com'] # Replace with up to 4 custom sponsorship URLs